services:
  system_orders:
    build:
      context: .
    container_name: order_system_app
    env_file:
      - .env.docker-compose
    depends_on:
      - db
    command: ["/system_orders/docker/wait-for-db.sh", "db", "/system_orders/docker/app.sh" ]
    ports:
      - 8003:8000
  db:
    image: postgres:17
    container_name: order_system_app_db
    environment:
      - POSTGRES_USER=${DB__USER}
      - POSTGRES_PASSWORD=${DB__PASSWORD}
      - POSTGRES_DB=${DB__NAME}

