# Generated by Django 4.2 on 2025-02-15 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orders',
            table='orders',
        ),
    ]
